name = "difusionayuda"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"





[vars]
SUPABASE_URL = "https://qjtvpifbrvdyhzgpobyl.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_C2bn9yZQwa0KFhCl-faRfg_ZuguwVr7"
